app_version: 0.3.0-preview.4
behavior_configs:
- base_wheel_speed: 16
  hide_cursor_on_click: false
  hide_location: bottom_left
  initial_overlay_monitor: last_used
  move_duration_ms: 1
  move_real_cursor_with_virtual: false
  multi_action_timeout_ms: 400
  name: main_behavior
  tap_threshold_ms: 200
  wheel_mode_auto_off_s: 10
  wheel_speed_multiplier: 4
  wheel_step_size: 100
  wheel_step_size_large: 500
classname: AppConfig
custom_monitor_assignments: []
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    num_cells_x: 20
    num_cells_y: 1
  - border_width: 1
    callback: build_cell_strings
    num_cells_x: 1
    num_cells_y: 20
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    num_cells_x: 2
    num_cells_y: 1
  mouse_action_keys: 12QWERTYUIOPASDFGHJKL
  name: monz
  strategy: subgrid
  subgrid_dims:
  - 8
  - 3
  subgrid_mouse_action_keys: QWERUIOPASDFJKL;ZXCVM,./
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    num_cells_x: 1
    num_cells_y: 26
  - border_width: 1.0
    callback: build_cell_strings
    num_cells_x: 26
    num_cells_y: 1
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    num_cells_x: 2
    num_cells_y: 1
  mouse_action_keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ
  name: vertical_alpha
  strategy: subgrid
  subgrid_dims:
  - 4
  - 6
  subgrid_mouse_action_keys: QWERASDFZXCVUIOPJKL;M,./
keymaps:
- entries:
    close UI element: OptionRight
    cycle click count: null
    cycle mouse action type: null
    cycle mouse button: null
    edit config: Tab
    execute mouse action: Space
    hide overlay: OptionRight
    hold for drag: CommandLeft
    hold for move: OptionLeft
    hold for right button: CommandRight
    release hold/drag: OptionRight
    repeat last mouse action: null
    show overlay: Control tap
    switch monitor left: ShiftLeft tap
    switch monitor right: ShiftRight tap
    toggle overlay: null
  name: mac
monitor_assignment_mode: single
name: ''
style_configs:
- always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.3
  background_rgba:
  - 0.00392156862745098
  - 0.00392156862745098
  - 0.00392156862745098
  - 0.5
  char_spacing_cell_width_ratio: 0.5
  char_spacing_font_size_ratio: 0.2
  char_spacing_strategy: font_size_relative
  cursor_drag_rgba:
  - 0.0
  - 0.5
  - 1.0
  - 0.7
  cursor_move_rgba:
  - 0.75
  - 0.41
  - 0.92
  - 0.7
  cursor_other_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.7
  cursor_rgba:
  - 1.0
  - 0.54
  - 0.0
  - 0.7
  cursor_right_button_rgba:
  - 0.92
  - 0.32
  - 0.32
  - 0.7
  cursor_size: 7
  font_size_multiplier: 0.2
  grid_line_style: lines
  grid_rgba:
  - 0.13333333333333333
  - 1.0
  - 0.00392156862745098
  - 0.2
  highlight_rgba:
  - 0.3568627450980392
  - 0.996078431372549
  - 0.03529411764705882
  - 0.5
  name: dark_bg
  show_initial_highlight: false
  subgrid_font_size_multiplier: 0.5
  subgrid_rgba:
  - 0.3803921568627451
  - 1.0
  - 0.00392156862745098
  - 0.2
  subgrid_text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.9
  text_rgba:
  - 0.996078431372549
  - 0.996078431372549
  - 0.996078431372549
  - 0.9
  text_shadow_blur_radius: 4
  text_shadow_offset:
  - 1
  - -1
  text_shadow_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  window_opacity: 0.9
