import = [
  "~/.config/alacritty/theme/catppuccin-mocha.toml",
]

[window]
opacity = 0.8
blur = true
decorations= "buttonless"
padding = {y = 0}

[selection]
save_to_clipboard = true

[colors.cursor]
cursor = "#eeeeee"
text = "#000000"

[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
