
set rtp +=~/.vim

command Sov so ~/.vimrc

if has('vim_starting')
  set nocompatible
endif

autocmd FileType php setlocal tabstop=4 softtabstop=4 shiftwidth=4
filetype plugin indent on
syntax on

set backspace=indent,eol,start
set history=100
set ignorecase
set smartcase
set title
set showcmd
set laststatus=2
set showmatch
set matchtime=1
set termencoding=utf8
set encoding=utf8
set fenc=utf8
set wrap
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2
set hlsearch
set incsearch
set nonumber
set noswapfile
set nobackup
set autoread
set hidden
set clipboard=unnamed
set cursorline
set fileencoding=utf-8
set fileencodings=utf-8
set fileformats=unix,dos,mac
set foldlevel=99
set bomb
set binary
set ttyfast
set ruler
set autoindent
set splitright
set splitbelow
set scrolloff=3
set laststatus=2
set modeline
set modelines=10
set titleold="Terminal"
set titlestring=%F
set statusline=%F%m%r%h%w%=(%{&ff}/%Y)\ (line\ %l\/%L,\ col\ %c)\
set noerrorbells visualbell t_vb=
set mouse=a
set whichwrap=b,s,h,l,<,>,[,]
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite
set shortmess+=c
set completeopt=menuone,noinsert,noselect,preview
set termguicolors
set ambiwidth=double
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

if has('nvim')
  set clipboard+=unnamedplus
  set guicursor=a:blinkon0
else
  set guicursor=i:blinkwait700-blinkon400-blinkoff250
	set clipboard+=unnamed,autoselect
endif
" Keys
let mapleader="\<Space>"
inoremap <silent> jj <ESC>
let g:fern#renderer = 'nerdfont'
nnoremap <C-n> :Fern . -reveal=% -drawer -toggle -width=40<CR>

nmap <Leader>q <Home>
nmap <Leader>e <End>
nmap <Leader>t :tabnew<CR>
nmap <Leader>w :tabclose<CR>
map K gt
map J gT

nmap <Leader><Leader> <Plug>BookmarkToggle
nmap <Leader>i <Plug>BookmarkAnnotate
nmap <Leader>a <Plug>BookmarkShowAll
nmap <Leader>j <Plug>BookmarkNext
nmap <Leader>k <Plug>BookmarkPrev
nmap <Leader>c <Plug>BookmarkClear
nmap <Leader>x <Plug>BookmarkClearAll
nmap <Leader>kk <Plug>BookmarkMoveUp
nmap <Leader>jj <Plug>BookmarkMoveDown
nmap <Leader>g <Plug>BookmarkMoveToLine

nnoremap <Leader>mn  :MemoNew<CR>
nnoremap <Leader>ml  :MemoList<CR>
nnoremap <Leader>mg  :MemoGrep<CR>
let g:memolist_memo_suffix = "md"
let g:memolist_ex_cmd = 'Fern'

nmap <Leader>l :FzfPreviewAllBuffersRpc<CR>

command! -nargs=* T split | wincmd j | resize 5 | terminal <args>
tnoremap <Esc> <C-\><C-n>
autocmd TermOpen * startinsert

augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
  autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END

let g:tagalong_filetypes = ['html', 'xml', 'jsx', 'eruby', 'ejs', 'eco', 'php', 'htmldjango', 'javascriptreact', 'typescriptreact', 'javascript', 'typescript', 'typescirpt.tsx']


" plugin
call plug#begin('~/.vim/plugged')
Plug 'glidenote/memolist.vim'
Plug 'itchyny/lightline.vim'
Plug 'tpope/vim-surround'
Plug 'ervandew/supertab'
Plug 'tomtom/tcomment_vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'lambdalisue/fern.vim'
Plug 'lambdalisue/fern-git-status.vim'
Plug 'lambdalisue/nerdfont.vim'
Plug 'lambdalisue/fern-renderer-nerdfont.vim'
Plug 'lambdalisue/glyph-palette.vim'
Plug 'MattesGroeger/vim-bookmarks'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'Raimondi/delimitMate'
Plug 'simeji/winresizer'
Plug 'AndrewRadev/tagalong.vim'

if has('nvim')
	Plug 'rebelot/kanagawa.nvim'
	Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
	Plug 'yuki-yano/fzf-preview.vim', { 'branch': 'release/rpc' }
	Plug 'phaazon/hop.nvim'
endif
call plug#end()

colorscheme kanagawa

augroup vimrc_syntax
  autocmd!
  highlight default ExtraWhitespace ctermbg=red guibg=red
  autocmd VimEnter,WinEnter,BufRead *
        \ call matchadd('ExtraWhitespace', "[\u2000-\u200B\u3000]")
augroup END
